# Generated by Django 5.1.1 on 2024-09-09 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importdatasource',
            name='path',
        ),
    ]
