# Generated by Django 5.1.1 on 2024-09-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_importdatasource_path'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportDataSetScript',
        ),
        migrations.AlterModelOptions(
            name='importdataset',
            options={'verbose_name_plural': 'Import Data Sets'},
        ),
        migrations.AlterModelOptions(
            name='importdatasource',
            options={'verbose_name_plural': 'Import Data Sources'},
        ),
        migrations.AddField(
            model_name='importdatasource',
            name='source_type',
            field=models.CharField(choices=[('bulk_upload', 'Bulk Upload'), ('web_api', 'Web API'), ('other', 'Other')], default='bulk'),
            preserve_default=False,
        ),
    ]
