# Generated by Django 5.1.1 on 2024-09-10 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_delete_importdatasetscript_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importdatasource',
            name='path',
            field=models.FilePathField(default='/opt', verbose_name='/opt'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='importdatasource',
            name='source_type',
            field=models.CharField(choices=[('bulk_upload', 'Bulk Upload'), ('web_api', 'Web API'), ('other', 'Other')], default='api'),
        ),
    ]
