# Generated by Django 5.1.1 on 2024-09-10 00:26

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_importdatasource_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importdatasource',
            name='path',
            field=models.FilePathField(default=pathlib.PurePosixPath('/home/eron/democracrm/democracrm')),
        ),
    ]
