# Generated by Django 5.1.1 on 2024-09-10 00:31

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_importdatasource_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importdatasource',
            name='path',
            field=models.FilePathField(path=pathlib.PurePosixPath('/home/eron/democracrm/democracrm')),
        ),
    ]
