# Generated by Django 5.1.1 on 2024-09-10 00:58

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_importdatasource_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importdatasource',
            name='path',
            field=models.FilePathField(allow_files=False, allow_folders=True, path=pathlib.PurePosixPath('/home/eron/democracrm/democracrm/data/imports'), recursive=True),
        ),
    ]
