# Generated by Django 4.1.2 on 2022-12-02 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lobbying', '0001_initial'),
        ('contacts', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('org_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organizationaccount')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='places.region')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('categories_enabled', models.BooleanField(default=False)),
                ('org_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organizationaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlatformCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=1)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizing.platform')),
            ],
            options={
                'verbose_name_plural': 'Platform Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField()),
                ('chapter', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='organizing.chapter')),
                ('contact', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='contacts.contact')),
                ('org_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organizationaccount')),
                ('user_account', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('voter', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='lobbying.voter')),
            ],
            options={
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('relationship', models.CharField(choices=[('ally', 'Ally'), ('opponent', 'Opponent'), ('unknown', 'Unknown')], default='unknown', max_length=255)),
                ('url', models.URLField(blank=True)),
                ('notes', models.TextField()),
                ('region', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='places.region')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.IntegerField(choices=[(5, 'Top'), (4, 'High'), (3, 'Medium'), (2, 'Low'), (1, 'None')], default=3)),
                ('status', models.CharField(choices=[('brainstorming', 'Brainstorming'), ('planned', 'Planned'), ('deferred', 'Deferred'), ('in-progress', 'In-Progress'), ('decision-time', 'Decision Time'), ('victory', 'Victory'), ('lost', 'Lost')], default='brainstorming', max_length=255)),
                ('is_public', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='organizing.platformcategory')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizing.platform')),
                ('targets', models.ManyToManyField(to='lobbying.publicoffice')),
            ],
            options={
                'ordering': ['category', '-priority', 'name'],
            },
        ),
    ]
