# Generated by Django 4.1.2 on 2022-11-25 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0001_initial'),
        ('organizing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='targets',
            field=models.ManyToManyField(to='lobbying.publicoffice'),
        ),
        migrations.AddField(
            model_name='person',
            name='voter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lobbying.voter'),
        ),
    ]
