# Generated by Django 4.1.2 on 2022-11-19 01:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_organization_created_by_and_more'),
        ('organizing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('categories_enabled', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accounts.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlatformCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='organizing.platform')),
            ],
            options={
                'verbose_name_plural': 'Platform Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.IntegerField(choices=[(5, 'Top'), (4, 'High'), (3, 'Medium'), (2, 'Low'), (1, 'None')], default=3)),
                ('status', models.CharField(blank=True, choices=[('brainstorming', 'Brainstorming'), ('planned', 'Planned'), ('deferred', 'Deferred'), ('in-progress', 'In-Progress'), ('decision-time', 'Decision Time'), ('victory', 'Victory'), ('lost', 'Lost')], max_length=255, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='organizing.platformcategory')),
            ],
            options={
                'ordering': ['category', '-priority', 'name'],
            },
        ),
    ]
