# Generated by Django 4.1.2 on 2022-12-04 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0005_alter_supportlevel_legislation'),
        ('contacts', '0002_alter_contact_birthday_alter_contact_notes_and_more'),
        ('organizing', '0002_alter_campaign_category_alter_campaign_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizing.chapter'),
        ),
        migrations.AlterField(
            model_name='person',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='person',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='voter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lobbying.voter'),
        ),
    ]
