# Generated by Django 4.1.2 on 2022-11-26 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        ('organizing', '0002_campaign_targets_person_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='places.region'),
        ),
    ]
