# Generated by Django 4.1.2 on 2022-11-19 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_organization_created_by_and_more'),
        ('core', '0010_contactinfo_mobile_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lobbying', '0008_alter_legislation_campaign_delete_campaign_and_more'),
        ('organizing', '0002_platform_platformcategory_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizing.chapter'),
        ),
        migrations.AddField(
            model_name='member',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.contactinfo'),
        ),
        migrations.AddField(
            model_name='member',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='voter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lobbying.voter'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='relationship',
            field=models.CharField(choices=[('ally', 'Ally'), ('opponent', 'Opponent'), ('unknown', 'Unknown')], default='unknown', max_length=255),
        ),
    ]
