# Generated by Django 4.1.2 on 2022-11-19 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_organization_created_by_and_more'),
        ('organizing', '0003_member_chapter_member_contact_member_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='name',
            field=models.CharField(default='Test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.organization'),
            preserve_default=False,
        ),
    ]
