# Generated by Django 4.1.4 on 2022-12-15 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lobbying", "0027_alter_legislationgroup_options_and_more"),
        ("organizing", "0003_alter_person_chapter_alter_person_contact_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="legislation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="lobbying.legislationgroup",
            ),
        ),
    ]
