# Generated by Django 4.1.2 on 2022-11-19 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_contactinfo_role'),
        ('organizing', '0004_chapter_name_chapter_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.geographicregion'),
            preserve_default=False,
        ),
    ]
