# Generated by Django 4.1.4 on 2022-12-20 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_organizationaccount_description_and_more"),
        ("organizing", "0005_campaign_end_date_campaign_start_date"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PlatformCategory",
            new_name="CampaignCategory",
        ),
        migrations.AlterModelOptions(
            name="campaigncategory",
            options={
                "ordering": ["order"],
                "verbose_name_plural": "Campaign Categories",
            },
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="platform",
        ),
        migrations.RemoveField(
            model_name="campaigncategory",
            name="platform",
        ),
        migrations.AddField(
            model_name="campaign",
            name="org_account",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.organizationaccount",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campaigncategory",
            name="org_account",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.organizationaccount",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organization",
            name="org_account",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.organizationaccount",
            ),
            preserve_default=False,
        ),
    ]
