# Generated by Django 4.1.2 on 2022-11-20 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_organization_primary_contact'),
        ('organizing', '0005_chapter_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizing.platformcategory'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='platformcategory',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizing.platform'),
        ),
    ]
