# Generated by Django 4.1.4 on 2022-12-21 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizing", "0006_rename_platformcategory_campaigncategory_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Platform",
        ),
    ]
