# Generated by Django 4.1.2 on 2022-11-20 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizing', '0007_alter_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='platform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='organizing.platform'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='platformcategory',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
