# Generated by Django 4.1.2 on 2022-11-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizing', '0008_campaign_platform_alter_platformcategory_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(default='Test', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('brainstorming', 'Brainstorming'), ('planned', 'Planned'), ('deferred', 'Deferred'), ('in-progress', 'In-Progress'), ('decision-time', 'Decision Time'), ('victory', 'Victory'), ('lost', 'Lost')], default='brainstorming', max_length=255),
        ),
    ]
