# Generated by Django 4.1.5 on 2023-01-13 10:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizing', '0009_organization_site_alter_person_user_account_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaignmilestone',
            options={'verbose_name_plural': 'Campaign Milestones'},
        ),
        migrations.AlterModelOptions(
            name='organizationgroup',
            options={'verbose_name_plural': 'Organization Groups'},
        ),
        migrations.AlterModelOptions(
            name='persongroup',
            options={'verbose_name_plural': 'Person Group'},
        ),
        migrations.RemoveField(
            model_name='organization',
            name='relationship',
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=50)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizing.organization')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizing.person')),
            ],
            options={
                'verbose_name_plural': 'Relationships',
            },
        ),
    ]
