# Generated by Django 4.1.2 on 2022-11-21 23:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_organization_primary_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_link_alter_geographicboundary_parent'),
        ('lobbying', '0010_alter_politicalsubdivision_office'),
        ('organizing', '0009_alter_campaign_name_alter_campaign_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Person',
        ),
    ]
