# Generated by Django 4.1.2 on 2022-11-22 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizing', '0010_rename_member_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'People'},
        ),
    ]
