# Generated by Django 4.1.5 on 2023-01-14 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizing', '0011_rename_organization_relationship_org_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='org_subject',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='person_subject',
        ),
        migrations.AddField(
            model_name='relationship',
            name='organization1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_relation', to='organizing.organization'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='organization2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_relation', to='organizing.organization'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='person1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_relation', to='organizing.person'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='person2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_relation', to='organizing.person'),
        ),
    ]
