# Generated by Django 4.1.5 on 2023-01-14 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizing', '0012_remove_relationship_org_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='organization1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_relations', to='organizing.organization'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='organization2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_relations', to='organizing.organization'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='person1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_relations', to='organizing.person'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='person2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_relations', to='organizing.person'),
        ),
    ]
