# Generated by Django 4.1.5 on 2023-01-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizing', '0013_alter_relationship_organization1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='incoming_field',
            field=models.CharField(default='person1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relationship',
            name='outgoing_field',
            field=models.CharField(default='organization1', max_length=50),
            preserve_default=False,
        ),
    ]
