# Generated by Django 4.1.2 on 2022-12-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contactgroup',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contactrole',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
