# Generated by Django 4.1.2 on 2022-11-17 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_organizationaccount'),
        ('accounts', '0002_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name_plural': 'Organizations'},
        ),
        migrations.AddField(
            model_name='organization',
            name='territory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.geographicarea'),
            preserve_default=False,
        ),
    ]
