# Generated by Django 4.1.2 on 2022-11-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_organization_options_organization_territory'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='created_by',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='updated_by',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_by',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
