# Generated by Django 4.1.2 on 2022-11-18 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organization_created_by_organization_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_by',
        ),
    ]
