# Generated by Django 4.1.2 on 2022-11-20 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_has_street_address_site_has_physical_address_and_more'),
        ('accounts', '0007_organization_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='primary_contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.contactinfo'),
            preserve_default=False,
        ),
    ]
