# Generated by Django 4.1.2 on 2022-11-13 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('has_street_address', models.BooleanField(default=False)),
                ('street_number', models.CharField(blank=True, max_length=10)),
                ('street_direction', models.CharField(blank=True, max_length=10)),
                ('street_name', models.CharField(blank=True, max_length=255)),
                ('street_suffix', models.CharField(blank=True, max_length=100)),
                ('unit_number', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('county', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.location')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.site')),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_prefix', models.CharField(blank=True, max_length=50)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('name_suffix', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('personal_phone', models.CharField(blank=True, max_length=15)),
                ('work_phone', models.CharField(blank=True, max_length=15)),
                ('personal_email', models.CharField(blank=True, max_length=255)),
                ('work_email', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.site')),
            ],
        ),
    ]
