# Generated by Django 4.1.2 on 2022-11-18 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_organization_options_organization_territory'),
        ('lobbying', '0002_alter_platform_organization'),
        ('core', '0002_delete_organizationaccount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeographicArea',
            new_name='GeographicBoundary',
        ),
        migrations.AlterModelOptions(
            name='geographicboundary',
            options={'verbose_name_plural': 'Geographic Boundaries'},
        ),
    ]
