# Generated by Django 4.1.2 on 2022-11-13 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_geographicarea'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geographicarea',
            options={'verbose_name_plural': 'Geographic Areas'},
        ),
        migrations.AlterField(
            model_name='geographicarea',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.geographicarea'),
        ),
    ]
