# Generated by Django 4.1.2 on 2022-11-18 01:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0005_remove_governingbody_type_publicoffice_type_and_more'),
        ('core', '0003_rename_geographicarea_geographicboundary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('twitter', 'Twitter'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn')], max_length=255)),
                ('handle', models.CharField(max_length=255)),
                ('voter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='lobbying.voter')),
            ],
            options={
                'verbose_name_plural': 'Social Media Accounts',
            },
        ),
    ]
