# Generated by Django 4.1.2 on 2022-11-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_geographicarea_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geographicarea',
            name='level',
            field=models.CharField(blank=True, choices=[('nation', 'Nation'), ('state', 'State'), ('county', 'County'), ('municipality', 'Municipality')], max_length=255, null=True),
        ),
    ]
