# Generated by Django 4.1.2 on 2022-11-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_geographicregion_alter_geographicboundary_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_by',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_by',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='created_by',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='updated_by',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='contactrole',
            name='created_by',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='contactrole',
            name='updated_by',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='geographicboundary',
            name='created_by',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='geographicboundary',
            name='updated_by',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='geographicregion',
            name='created_by',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='geographicregion',
            name='updated_by',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='location',
            name='created_by',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='location',
            name='updated_by',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='site',
            name='created_by',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='site',
            name='updated_by',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='created_by',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='updated_by',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
