# Generated by Django 4.1.2 on 2022-11-13 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contactrole_note_text_contactinfo_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name_plural': 'Contact Info'},
        ),
        migrations.AlterModelOptions(
            name='contactrole',
            options={'verbose_name_plural': 'Contact Roles'},
        ),
    ]
