# Generated by Django 4.1.2 on 2022-11-18 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_comment_created_by_comment_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='contactrole',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='contactrole',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='geographicboundary',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='geographicboundary',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='geographicregion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='geographicregion',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='location',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='location',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='site',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='site',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='updated_by',
        ),
    ]
