# Generated by Django 4.1.2 on 2022-11-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_comment_created_by_remove_comment_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geographicregion',
            name='boundaries',
            field=models.ManyToManyField(to='core.geographicboundary'),
        ),
        migrations.AddField(
            model_name='geographicregion',
            name='name',
            field=models.CharField(default='Test', max_length=255),
            preserve_default=False,
        ),
    ]
