# Generated by Django 4.1.2 on 2022-11-15 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0023_organization_alter_campaign_options'),
        ('core', '0007_rename_note_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organization',
            new_name='OrganizationAccount',
        ),
    ]
