# Generated by Django 4.1.2 on 2022-11-18 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_geographicregion_boundaries_geographicregion_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geographicregion',
            options={'verbose_name_plural': 'Geographic Regions'},
        ),
    ]
