# Generated by Django 4.1.2 on 2022-11-15 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_organization_organizationaccount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationaccount',
            options={'verbose_name_plural': 'Organization Accounts'},
        ),
    ]
