# Generated by Django 4.1.2 on 2022-11-19 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_contactinfo_mobile_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.contactrole'),
        ),
    ]
