# Generated by Django 4.1.2 on 2022-11-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_site_city_alter_site_county_alter_site_state_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='has_street_address',
            new_name='has_physical_address',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='city',
            new_name='physical_city',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='county',
            new_name='physical_county',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='latitude',
            new_name='physical_latitude',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='longitude',
            new_name='physical_longitude',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='state',
            new_name='physical_state',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='street_direction',
            new_name='physical_street_direction',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='street_name',
            new_name='physical_street_name',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='street_number',
            new_name='physical_street_number',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='street_suffix',
            new_name='physical_street_suffix',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='unit_number',
            new_name='physical_unit_number',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='zip_code',
            new_name='physical_zip_code',
        ),
        migrations.AddField(
            model_name='site',
            name='has_mailing_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='mailing_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='mailing_county',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='mailing_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='mailing_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='mailing_po_box',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='mailing_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='mailing_street_direction',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='mailing_street_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='mailing_street_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='mailing_street_suffix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='mailing_unit_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='mailing_zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
