# Generated by Django 4.1.2 on 2022-11-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_link_alter_geographicboundary_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='personal_fax',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='work_fax',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='unit',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
