# Generated by Django 4.1.2 on 2022-11-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_contactinfo_personal_fax_contactinfo_work_fax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
