# Generated by Django 4.1.2 on 2022-11-22 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_organization_primary_contact'),
        ('core', '0016_alter_location_name_alter_location_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='geographicregion',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.organization'),
            preserve_default=False,
        ),
    ]
