# Generated by Django 4.1.2 on 2022-11-25 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_organization_primary_contact'),
        ('lobbying', '0018_alter_interpersonaltie_options'),
        ('organizing', '0012_campaign_targets'),
        ('core', '0017_geographicregion_organization'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeographicBoundary',
            new_name='Boundary',
        ),
        migrations.RenameModel(
            old_name='GeographicRegion',
            new_name='Region',
        ),
        migrations.AlterModelOptions(
            name='boundary',
            options={'verbose_name_plural': 'Boundaries'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name_plural': 'Regions'},
        ),
    ]
