# Generated by Django 4.0.6 on 2022-08-02 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactinfo_note_organization_site_address_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='address_1',
        ),
        migrations.RemoveField(
            model_name='site',
            name='address_2',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='name_prefix',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='name_suffix',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='personal_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='personal_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.site'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='work_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='work_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='location',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='county',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='site',
            name='latitude',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='longitude',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='street_direction',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='site',
            name='street_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='site',
            name='street_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='site',
            name='street_suffix',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='site',
            name='unit_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
