# Generated by Django 4.1.2 on 2022-11-13 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoverningBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PoliticalParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Political Parties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PoliticalSubdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('district', models.IntegerField(blank=True, null=True)),
                ('seats', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name')),
                ('sex', models.CharField(blank=True, max_length=10, null=True, verbose_name='Sex')),
                ('birth_date', models.DateField(blank=True, verbose_name='Birth Date')),
                ('initial_registration', models.DateField(blank=True, verbose_name='Initial Registration')),
                ('current_registration', models.DateField(blank=True, verbose_name='Current Registration')),
                ('address_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Number')),
                ('address_street_direction', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Street Direction')),
                ('address_street_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Street Name')),
                ('address_street_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Street Type')),
                ('address_unit', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Unit')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('zip_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='ZIP Code')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='Phone Number')),
                ('email_address', models.CharField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lobbying.politicalparty')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('twitter', 'Twitter'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn')], max_length=255)),
                ('handle', models.CharField(max_length=255)),
                ('voter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='lobbying.voter')),
            ],
            options={
                'verbose_name_plural': 'Social Media Accounts',
            },
        ),
        migrations.CreateModel(
            name='PublicOfficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix_name', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('suffix_name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_elected', models.BooleanField(default=True)),
                ('official_type', models.CharField(default='Legislator', max_length=100)),
                ('subdivision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='lobbying.politicalsubdivision')),
            ],
        ),
    ]
