# Generated by Django 4.1.2 on 2022-11-17 01:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.IntegerField(choices=[(5, 'Top'), (4, 'High'), (3, 'Medium'), (2, 'Low'), (1, 'None')], default=3)),
                ('status', models.CharField(blank=True, choices=[('brainstorming', 'Brainstorming'), ('planned', 'Planned'), ('deferred', 'Deferred'), ('in-progress', 'In-Progress'), ('decision-time', 'Decision Time'), ('victory', 'Victory'), ('lost', 'Lost')], max_length=255, null=True)),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['category', '-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GoverningBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, choices=[('legislative', 'Legislative'), ('executive', 'Executive'), ('judicial', 'Judicial')], max_length=255, null=True)),
                ('level', models.CharField(choices=[('federal', 'Federal'), ('state', 'State'), ('county', 'County'), ('municipal', 'Municipal')], max_length=255)),
                ('geographic_area', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.geographicarea')),
            ],
            options={
                'verbose_name_plural': 'Governing Bodies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(blank=True, choices=[('ally', 'Ally'), ('opponent', 'Opponent'), ('unknown', 'Unknown')], max_length=255, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('categories_enabled', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.organizationaccount')),
            ],
        ),
        migrations.CreateModel(
            name='PoliticalParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Political Parties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PoliticalSubdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('district', models.IntegerField(blank=True, null=True)),
                ('seats', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Political Subdivisions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PublicOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('governing_body', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lobbying.governingbody')),
            ],
            options={
                'verbose_name_plural': 'Public Offices',
            },
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, verbose_name='UUID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name')),
                ('sex', models.CharField(blank=True, max_length=10, null=True, verbose_name='Sex')),
                ('birth_date', models.DateField(blank=True, verbose_name='Birth Date')),
                ('initial_registration', models.DateField(blank=True, verbose_name='Initial Registration')),
                ('current_registration', models.DateField(blank=True, verbose_name='Current Registration')),
                ('address_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Number')),
                ('address_street_direction', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Street Direction')),
                ('address_street_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Street Name')),
                ('address_street_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Street Type')),
                ('address_unit', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Unit')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('zip_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='ZIP Code')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='Phone Number')),
                ('email_address', models.CharField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lobbying.politicalparty')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('twitter', 'Twitter'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn')], max_length=255)),
                ('handle', models.CharField(max_length=255)),
                ('voter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='lobbying.voter')),
            ],
            options={
                'verbose_name_plural': 'Social Media Accounts',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lobbying.governingbody')),
            ],
        ),
        migrations.CreateModel(
            name='PublicOfficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('prefix_name', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('suffix_name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_elected', models.BooleanField(default=True)),
                ('service_start', models.DateField(blank=True, null=True)),
                ('service_end', models.DateField(blank=True, null=True)),
                ('role', models.CharField(choices=[('legislative', 'Legislative'), ('executive', 'Executive'), ('judicial', 'Judicial'), ('administrative', 'Administrative'), ('clerical', 'Clerical')], default='Legislator', max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lobbying.publicoffice')),
                ('subdivision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='lobbying.politicalsubdivision')),
            ],
            options={
                'verbose_name_plural': 'Public Officials',
            },
        ),
        migrations.AddField(
            model_name='politicalsubdivision',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='lobbying.publicoffice'),
        ),
        migrations.CreateModel(
            name='PlatformCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lobbying.platform')),
            ],
            options={
                'verbose_name_plural': 'Platform Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Legislation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('proposed', 'Proposed'), ('in-committee', 'In Committee'), ('in-debate', 'In Debate'), ('voting-on', 'Voting On'), ('adopted', 'Adopted'), ('rejected', 'Rejected')], max_length=255, null=True)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lobbying.governingbody')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lobbying.campaign')),
                ('committee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='lobbying.committee')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='lobbying.session')),
            ],
            options={
                'verbose_name_plural': 'Legislation',
            },
        ),
        migrations.AddField(
            model_name='committee',
            name='body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='lobbying.governingbody'),
        ),
        migrations.AddField(
            model_name='committee',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lobbying.publicoffice'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='lobbying.platformcategory'),
        ),
    ]
