# Generated by Django 5.1.1 on 2024-12-24 01:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegislationTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField()),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('legislation', models.ManyToManyField(blank=True, to='lobbying.legislation')),
            ],
            options={
                'verbose_name_plural': 'Legislation Tracker',
            },
        ),
    ]
