# Generated by Django 4.1.2 on 2022-12-02 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizing', '0001_initial'),
        ('lobbying', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportlevel',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='organizing.campaign'),
            preserve_default=False,
        ),
    ]
