# Generated by Django 4.1.2 on 2022-11-17 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization'),
        ('lobbying', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accounts.organization'),
        ),
    ]
