# Generated by Django 4.1.2 on 2022-11-13 00:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='UUID'),
        ),
    ]
