# Generated by Django 4.1.2 on 2022-11-13 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0002_voter_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='governingbody',
            options={'ordering': ['name'], 'verbose_name_plural': 'Governing Bodies'},
        ),
        migrations.AlterModelOptions(
            name='politicalsubdivision',
            options={'ordering': ['name'], 'verbose_name_plural': 'Political Subdivisions'},
        ),
        migrations.AlterModelOptions(
            name='publicofficial',
            options={'verbose_name_plural': 'Public Officials'},
        ),
        migrations.AddField(
            model_name='politicalsubdivision',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='lobbying.politicalsubdivision'),
        ),
    ]
