# Generated by Django 4.1.2 on 2022-11-18 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0002_alter_platform_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicofficial',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='lobbying.publicoffice'),
        ),
    ]
