# Generated by Django 4.1.2 on 2022-11-13 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_geographicarea_options_and_more'),
        ('lobbying', '0003_alter_governingbody_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='governingbody',
            name='geographic_area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='core.geographicarea'),
            preserve_default=False,
        ),
    ]
