# Generated by Django 4.1.2 on 2022-12-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0003_alter_publicofficial_service_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicalsubdivision',
            name='district',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
