# Generated by Django 4.0.6 on 2022-10-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0004_politicalsubdivision_seats'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoverningBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
