# Generated by Django 4.1.2 on 2022-11-18 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0004_rename_geographic_area_governingbody_boundary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='governingbody',
            name='type',
        ),
        migrations.AddField(
            model_name='publicoffice',
            name='type',
            field=models.CharField(choices=[('legislative', 'Legislative'), ('executive', 'Executive'), ('judicial', 'Judicial'), ('other', 'Other')], default='legislative', max_length=255),
        ),
        migrations.AlterField(
            model_name='publicoffice',
            name='governing_body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lobbying.governingbody'),
        ),
        migrations.DeleteModel(
            name='SocialMediaAccount',
        ),
    ]
