# Generated by Django 4.1.2 on 2022-11-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0005_governingbody_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='governingbody',
            name='level',
            field=models.CharField(choices=[('federal', 'Federal'), ('state', 'State'), ('county', 'County'), ('municipal', 'Municipal')], default='federal', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='governingbody',
            name='type',
            field=models.CharField(blank=True, choices=[('legislative', 'Legislative'), ('executive', 'Executive'), ('judicial', 'Judicial')], max_length=255, null=True),
        ),
    ]
