# Generated by Django 4.1.4 on 2022-12-09 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lobbying", "0005_alter_supportlevel_legislation"),
    ]

    operations = [
        migrations.AddField(
            model_name="politicalparty",
            name="abbreviation",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="politicalparty",
            name="initial",
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
