# Generated by Django 4.0.6 on 2022-10-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0005_governingbody'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicalsubdivision',
            name='district',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
