# Generated by Django 4.1.2 on 2022-11-18 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0005_remove_governingbody_type_publicoffice_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
