# Generated by Django 4.1.2 on 2022-11-19 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0006_delete_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='category',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='platformcategory',
            name='platform',
        ),
    ]
