# Generated by Django 4.1.2 on 2022-11-13 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0006_governingbody_level_alter_governingbody_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('governing_body', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lobbying.governingbody')),
            ],
            options={
                'verbose_name_plural': 'Public Offices',
            },
        ),
    ]
