# Generated by Django 4.1.2 on 2022-11-19 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizing', '0002_platform_platformcategory_campaign'),
        ('lobbying', '0007_remove_campaign_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislation',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='organizing.campaign'),
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
        migrations.DeleteModel(
            name='PlatformCategory',
        ),
    ]
