# Generated by Django 4.1.4 on 2022-12-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lobbying", "0007_rename_body_committee_governing_body_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="legislativesession",
            options={"verbose_name_plural": "Legislative Sessions"},
        ),
        migrations.AddField(
            model_name="publicofficial",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="publicofficial",
            name="is_seeking_reelection",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="publicofficial",
            name="official_profile_photo_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="publicofficial",
            name="official_profile_thumbnail_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="publicofficial",
            name="official_profile_url",
            field=models.URLField(blank=True),
        ),
    ]
