# Generated by Django 4.1.2 on 2022-11-13 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0007_publicoffice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politicalsubdivision',
            name='parent',
        ),
        migrations.AddField(
            model_name='politicalsubdivision',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='lobbying.publicoffice'),
        ),
    ]
