# Generated by Django 4.1.2 on 2022-11-11 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0008_remove_voter_id_voter_first_name_voter_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='party',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='lobbying.politicalparty'),
            preserve_default=False,
        ),
    ]
