# Generated by Django 4.1.4 on 2022-12-10 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lobbying", "0008_alter_legislativesession_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publicofficial",
            options={
                "ordering": ["last_name"],
                "verbose_name_plural": "Public Officials",
            },
        ),
    ]
