# Generated by Django 4.1.2 on 2022-11-13 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0008_remove_politicalsubdivision_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicofficial',
            name='office',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='lobbying.publicoffice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicofficial',
            name='title',
            field=models.CharField(default='Mayor', max_length=255),
            preserve_default=False,
        ),
    ]
