# Generated by Django 4.1.2 on 2022-11-21 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0009_publicoffice_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicalsubdivision',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lobbying.publicoffice'),
        ),
    ]
