# Generated by Django 4.1.2 on 2022-11-13 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0009_publicofficial_office_publicofficial_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicofficial',
            old_name='official_type',
            new_name='role',
        ),
    ]
