# Generated by Django 4.1.4 on 2022-12-10 04:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("lobbying", "0009_alter_publicofficial_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicOfficialGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="lobbying.publicofficialgroup",
                        verbose_name="parent",
                    ),
                ),
                (
                    "public_officials",
                    models.ManyToManyField(blank=True, to="lobbying.publicofficial"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
