# Generated by Django 4.1.2 on 2022-11-11 03:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0009_voter_party'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='politicalparty',
            options={'ordering': ['name'], 'verbose_name_plural': 'Political Parties'},
        ),
        migrations.AddField(
            model_name='voter',
            name='address_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='address_street_direction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='address_street_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='address_street_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 11, 3, 15, 40, 424274, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='current_registration',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 11, 3, 16, 0, 435177, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='initial_registration',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 11, 3, 16, 7, 849745, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='sex',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='zip_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
