# Generated by Django 4.1.2 on 2022-11-22 03:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizing', '0011_alter_person_options'),
        ('lobbying', '0010_alter_politicalsubdivision_office'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(choices=[('strongly_supports', 'Strongly Supports'), ('supports', 'Supports'), ('undecided', 'Undecided'), ('opposes', 'Opposes'), ('strongly_opposed', 'Strongly Opposed')], on_delete=django.db.models.deletion.PROTECT, to='organizing.campaign')),
                ('legislation', models.ForeignKey(blank=True, choices=[('strongly_supports', 'Strongly Supports'), ('supports', 'Supports'), ('undecided', 'Undecided'), ('opposes', 'Opposes'), ('strongly_opposed', 'Strongly Opposed')], null=True, on_delete=django.db.models.deletion.PROTECT, to='lobbying.legislation')),
                ('official', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lobbying.publicofficial')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
