# Generated by Django 4.1.2 on 2022-11-11 09:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0010_alter_politicalparty_options_voter_address_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
