# Generated by Django 4.1.2 on 2022-11-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0010_rename_official_type_publicofficial_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicofficial',
            name='role',
            field=models.CharField(choices=[('legislative', 'Legislative'), ('executive', 'Executive'), ('judicial', 'Judicial'), ('administrative', 'Administrative'), ('clerical', 'Clerical')], default='Legislator', max_length=100),
        ),
    ]
