# Generated by Django 4.1.2 on 2022-11-11 10:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0011_voter_phone_number_alter_voter_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='address_unit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='address_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Number'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='address_street_direction',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Street Direction'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='address_street_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Street Name'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='address_street_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Street Type'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='birth_date',
            field=models.DateField(blank=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='current_registration',
            field=models.DateField(blank=True, verbose_name='Current Registration'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='initial_registration',
            field=models.DateField(blank=True, verbose_name='Initial Registration'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='sex',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='zip_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ZIP Code'),
        ),
    ]
