# Generated by Django 4.1.2 on 2022-11-22 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizing', '0011_alter_person_options'),
        ('lobbying', '0011_supportlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportlevel',
            name='campaign_support',
            field=models.CharField(choices=[('strongly_supports', 'Strongly Supports'), ('supports', 'Supports'), ('undecided', 'Undecided'), ('opposes', 'Opposes'), ('strongly_opposed', 'Strongly Opposed')], default='undecided', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportlevel',
            name='legislation_support',
            field=models.CharField(choices=[('strongly_supports', 'Strongly Supports'), ('supports', 'Supports'), ('undecided', 'Undecided'), ('opposes', 'Opposes'), ('strongly_opposed', 'Strongly Opposed')], default='undecided', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supportlevel',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizing.campaign'),
        ),
        migrations.AlterField(
            model_name='supportlevel',
            name='legislation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lobbying.legislation'),
        ),
    ]
