# Generated by Django 4.1.4 on 2022-12-11 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lobbying", "0012_politicalsubdivision_boundary_legislationgroup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicofficial",
            name="political_party",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="lobbying.politicalparty",
            ),
        ),
        migrations.AlterField(
            model_name="publicofficial",
            name="political_subdivision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="lobbying.politicalsubdivision",
            ),
        ),
        migrations.AlterField(
            model_name="publicofficial",
            name="public_office",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="lobbying.publicoffice",
            ),
        ),
        migrations.AlterField(
            model_name="supportlevel",
            name="legislation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="lobbying.legislationgroup",
            ),
        ),
    ]
