# Generated by Django 4.1.2 on 2022-11-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0012_voter_address_unit_alter_voter_address_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=255)),
                ('handle', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='voter',
            name='email_address',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='address_unit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Unit'),
        ),
    ]
