# Generated by Django 4.1.2 on 2022-11-13 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0012_platformcategory_platform_campaign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='title',
            new_name='name',
        ),
    ]
