# Generated by Django 4.1.2 on 2022-11-13 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0013_rename_title_campaign_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platformcategory',
            options={'verbose_name_plural': 'Platform Categories'},
        ),
    ]
