# Generated by Django 4.1.4 on 2022-12-11 15:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("lobbying", "0013_alter_publicofficial_political_party_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicOfficialRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_elected", models.BooleanField(default=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("legislative", "Legislative"),
                            ("executive", "Executive"),
                            ("judicial", "Judicial"),
                            ("administrative", "Administrative"),
                            ("clerical", "Clerical"),
                        ],
                        default="legislative",
                        max_length=100,
                    ),
                ),
                ("service_start", models.DateField(blank=True, null=True)),
                ("service_end", models.DateField(blank=True, null=True)),
                ("official_profile_url", models.URLField(blank=True)),
                ("official_profile_thumbnail_url", models.URLField(blank=True)),
                ("official_profile_photo_url", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "political_subdivision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="lobbying.politicalsubdivision",
                    ),
                ),
                (
                    "public_office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="lobbying.publicoffice",
                    ),
                ),
                (
                    "public_official",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="lobbying.publicofficial",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
