# Generated by Django 4.1.4 on 2022-12-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lobbying", "0014_publicofficialrole"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publicofficialrole",
            options={"verbose_name_plural": "Public Official Roles"},
        ),
        migrations.AddField(
            model_name="publicofficialrole",
            name="is_leadership",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="publicofficialrole",
            name="leadership_title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
