# Generated by Django 4.1.2 on 2022-11-13 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0014_alter_platformcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformcategory',
            name='platform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='lobbying.platform'),
            preserve_default=False,
        ),
    ]
