# Generated by Django 4.1.2 on 2022-11-14 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0015_platformcategory_platform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platformcategory',
            options={'ordering': ['order'], 'verbose_name_plural': 'Platform Categories'},
        ),
        migrations.AddField(
            model_name='campaign',
            name='priority',
            field=models.CharField(blank=True, choices=[('top', 'Top'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=255, null=True),
        ),
    ]
