# Generated by Django 4.1.2 on 2022-11-14 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0016_alter_platformcategory_options_campaign_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
