# Generated by Django 4.1.4 on 2022-12-12 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0005_alter_location_options_alter_sitegroup_options"),
        ("lobbying", "0016_committee_parent_committeerole"),
    ]

    operations = [
        migrations.AddField(
            model_name="voter",
            name="county",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="county_voters",
                to="places.boundary",
            ),
        ),
        migrations.AddField(
            model_name="voter",
            name="municipality",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="municipal_voters",
                to="places.boundary",
            ),
        ),
        migrations.AlterField(
            model_name="committeerole",
            name="type",
            field=models.CharField(
                choices=[
                    ("chair", "Chair"),
                    ("vice-chair", "Vice-Chair"),
                    ("ex-officio", "Ex-Officio"),
                    ("member", "Member"),
                ],
                default="member",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="voter",
            name="state",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="state_voters",
                to="places.boundary",
            ),
        ),
    ]
