# Generated by Django 4.1.2 on 2022-11-24 16:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0016_committee_created_on_committee_updated_on_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='LegislativeSession',
        ),
        migrations.CreateModel(
            name='InterpersonalTie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('tie_strength', models.CharField(choices=[('strong', 'Strong'), ('weak', 'Weak'), ('invisible', 'Invisible'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('tie_affinity', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('official1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ties_from', to='lobbying.publicofficial')),
                ('official2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ties_to', to='lobbying.publicofficial')),
            ],
        ),
    ]
