# Generated by Django 4.1.2 on 2022-11-24 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0017_rename_session_legislativesession_interpersonaltie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interpersonaltie',
            options={'verbose_name_plural': 'Interpersonal Ties'},
        ),
    ]
