# Generated by Django 4.1.4 on 2022-12-12 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0005_alter_location_options_alter_sitegroup_options"),
        ("lobbying", "0017_voter_county_voter_municipality_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="county",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="county_voters",
                to="places.boundary",
            ),
        ),
        migrations.AlterField(
            model_name="voter",
            name="id",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="voter",
            name="municipality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="municipal_voters",
                to="places.boundary",
            ),
        ),
        migrations.AlterField(
            model_name="voter",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="state_voters",
                to="places.boundary",
            ),
        ),
    ]
