# Generated by Django 4.1.2 on 2022-11-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0018_alter_campaign_options_alter_campaign_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicofficial',
            name='service_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='publicofficial',
            name='service_start',
            field=models.DateField(null=True),
        ),
    ]
