# Generated by Django 4.1.4 on 2022-12-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lobbying", "0018_alter_voter_county_alter_voter_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="voter",
            old_name="address_street_direction",
            new_name="physical_address_street_direction",
        ),
        migrations.RenameField(
            model_name="voter",
            old_name="address_street_name",
            new_name="physical_address_street_name",
        ),
        migrations.RenameField(
            model_name="voter",
            old_name="address_number",
            new_name="physical_address_street_number",
        ),
        migrations.RenameField(
            model_name="voter",
            old_name="address_unit",
            new_name="physical_address_unit",
        ),
        migrations.RenameField(
            model_name="voter",
            old_name="city",
            new_name="physical_city",
        ),
        migrations.RenameField(
            model_name="voter",
            old_name="county",
            new_name="physical_county",
        ),
        migrations.RenameField(
            model_name="voter",
            old_name="municipality",
            new_name="physical_municipality",
        ),
        migrations.RenameField(
            model_name="voter",
            old_name="state",
            new_name="physical_state",
        ),
        migrations.RenameField(
            model_name="voter",
            old_name="zip_code",
            new_name="physical_zip_code",
        ),
        migrations.RemoveField(
            model_name="voter",
            name="address_street_type",
        ),
        migrations.AddField(
            model_name="voter",
            name="mailing_address",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Mailing Address"
            ),
        ),
        migrations.AddField(
            model_name="voter",
            name="mailing_address_supplement",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Mailing Address Supplement"
            ),
        ),
        migrations.AddField(
            model_name="voter",
            name="mailing_city",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Mailing City"
            ),
        ),
        migrations.AddField(
            model_name="voter",
            name="mailing_state",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Mailing State"
            ),
        ),
        migrations.AddField(
            model_name="voter",
            name="mailing_zip_code",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Mailing ZIP Code"
            ),
        ),
        migrations.AddField(
            model_name="voter",
            name="physical_address_street_suffix",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="voter",
            name="physical_address_supplement",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Address Supplement"
            ),
        ),
        migrations.AddField(
            model_name="voter",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                max_length=20,
            ),
        ),
    ]
