# Generated by Django 4.1.4 on 2022-12-13 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "lobbying",
            "0019_rename_address_street_direction_voter_physical_address_street_direction_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PublicOfficialRole",
            new_name="PublicOfficialPosition",
        ),
        migrations.AlterModelOptions(
            name="publicofficialposition",
            options={"verbose_name_plural": "Public Official Positions"},
        ),
    ]
