# Generated by Django 4.1.2 on 2022-11-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0019_publicofficial_service_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicofficial',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicofficial',
            name='service_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicofficial',
            name='service_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
