# Generated by Django 4.1.2 on 2022-11-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0020_publicofficial_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-priority']},
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(blank=True, choices=[('brainstorming', 'Brainstorming'), ('planned', 'Planned'), ('deferred', 'Deferred'), ('in-progress', 'In-Progress'), ('decision-time', 'Decision Time'), ('victory', 'Victory'), ('lost', 'Lost')], max_length=255, null=True),
        ),
    ]
