# Generated by Django 4.1.4 on 2022-12-13 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lobbying", "0020_rename_publicofficialrole_publicofficialposition_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="voter",
            old_name="physical_address_street_suffix",
            new_name="physical_address_street_number_suffix",
        ),
    ]
