# Generated by Django 4.1.2 on 2022-11-15 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0022_alter_campaign_options_remove_campaign_is_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['category', '-priority', 'name']},
        ),
    ]
