# Generated by Django 4.1.4 on 2022-12-14 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lobbying", "0022_rename_physical_county_voter_county_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="voter",
            old_name="initial_registration",
            new_name="initial_registration_date",
        ),
        migrations.RenameField(
            model_name="voter",
            old_name="current_registration",
            new_name="last_registration_date",
        ),
    ]
