# Generated by Django 4.1.4 on 2022-12-14 02:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "lobbying",
            "0023_rename_initial_registration_voter_initial_registration_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="voter",
            name="data_export_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="voter",
            name="last_election_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="voter",
            name="last_voting_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="voter",
            name="voter_polling_place",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="voter",
            name="voter_precinct",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="voter",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Birth Date"),
        ),
        migrations.AlterField(
            model_name="voter",
            name="initial_registration_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Initial Registration"
            ),
        ),
        migrations.AlterField(
            model_name="voter",
            name="last_registration_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Current Registration"
            ),
        ),
    ]
