# Generated by Django 4.1.2 on 2022-11-15 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0024_organization_relationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legislation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(null=True)),
                ('status', models.CharField(blank=True, choices=[('proposed', 'Proposed'), ('in-committee', 'In Committee'), ('in-debate', 'In Debate'), ('voting-on', 'Voting On'), ('adopted', 'Adopted'), ('rejected', 'Rejected')], max_length=255, null=True)),
            ],
        ),
    ]
