# Generated by Django 4.1.2 on 2022-11-15 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0025_legislation'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislation',
            name='campaign',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, to='lobbying.campaign'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='legislation',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
