# Generated by Django 4.1.2 on 2022-11-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0026_legislation_campaign_alter_legislation_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legislation',
            options={'verbose_name_plural': 'Legislation'},
        ),
        migrations.RenameField(
            model_name='legislation',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='legislation',
            name='bill_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
