# Generated by Django 4.1.2 on 2022-11-15 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0027_alter_legislation_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legislation',
            old_name='bill_name',
            new_name='number',
        ),
    ]
