# Generated by Django 4.1.4 on 2022-12-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_alter_contact_birthday_alter_contact_notes_and_more"),
        ("lobbying", "0027_alter_legislationgroup_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicofficial",
            name="contacts",
            field=models.ManyToManyField(blank=True, to="contacts.contact"),
        ),
    ]
