# Generated by Django 5.0.7 on 2024-07-29 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0028_publicofficial_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicoffice',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='lobbying.publicoffice', verbose_name='parent'),
        ),
    ]
