# Generated by Django 4.1.2 on 2022-11-15 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0028_rename_bill_name_legislation_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislation',
            name='body',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='lobbying.governingbody'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lobbying.governingbody')),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lobbying.publicoffice')),
            ],
        ),
        migrations.AddField(
            model_name='legislation',
            name='committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='lobbying.committee'),
        ),
        migrations.AddField(
            model_name='legislation',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='lobbying.session'),
            preserve_default=False,
        ),
    ]
