# Generated by Django 5.0.7 on 2024-07-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0029_publicoffice_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicoffice',
            old_name='type',
            new_name='office_type',
        ),
        migrations.AddField(
            model_name='publicoffice',
            name='house_type',
            field=models.CharField(choices=[('unicameral', 'Unicameral'), ('bicameral', 'Bicameral'), ('tricameral', 'Tricameral'), ('tetracameral', 'Tetracameral')], default='unicameral', max_length=255),
        ),
    ]
