# Generated by Django 4.1.2 on 2022-11-15 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0030_alter_legislation_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legislation',
            name='session',
        ),
    ]
