# Generated by Django 5.1.1 on 2024-09-09 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0030_rename_type_publicoffice_office_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicoffice',
            old_name='house_type',
            new_name='chamber_type',
        ),
    ]
