# Generated by Django 5.1.1 on 2024-12-05 01:50

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('has_physical_address', models.BooleanField(default=False)),
                ('physical_street_number', models.CharField(blank=True, max_length=100)),
                ('physical_street_direction', models.CharField(blank=True, max_length=100)),
                ('physical_street_name', models.CharField(blank=True, max_length=100)),
                ('physical_street_suffix', models.CharField(blank=True, max_length=100)),
                ('physical_unit_number', models.CharField(blank=True, max_length=100)),
                ('physical_city', models.CharField(blank=True, max_length=100)),
                ('physical_state', models.CharField(blank=True, max_length=100)),
                ('physical_zip_code', models.CharField(blank=True, max_length=100)),
                ('physical_county', models.CharField(blank=True, max_length=100)),
                ('physical_latitude', models.FloatField(blank=True, max_length=100, null=True)),
                ('physical_longitude', models.FloatField(blank=True, max_length=100, null=True)),
                ('has_mailing_address', models.BooleanField(default=False)),
                ('mailing_street_number', models.CharField(blank=True, max_length=100)),
                ('mailing_street_direction', models.CharField(blank=True, max_length=100)),
                ('mailing_street_name', models.CharField(blank=True, max_length=100)),
                ('mailing_street_suffix', models.CharField(blank=True, max_length=100)),
                ('mailing_unit_number', models.CharField(blank=True, max_length=100)),
                ('mailing_po_box', models.CharField(blank=True, max_length=100)),
                ('mailing_city', models.CharField(blank=True, max_length=100)),
                ('mailing_state', models.CharField(blank=True, max_length=100)),
                ('mailing_zip_code', models.CharField(blank=True, max_length=100)),
                ('mailing_county', models.CharField(blank=True, max_length=100)),
                ('mailing_latitude', models.FloatField(blank=True, null=True)),
                ('mailing_longitude', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Sites',
            },
        ),
        migrations.CreateModel(
            name='Boundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('nation', 'National'), ('state', 'State'), ('county', 'County'), ('municipality', 'Municipality'), ('upper_legislative', 'Upper Legislative'), ('lower_legislative', 'Lower Legislative'), ('organizational', 'Organizational')], max_length=100)),
                ('is_national_capital', models.BooleanField(null=True)),
                ('is_state_capital', models.BooleanField(null=True)),
                ('is_county_capital', models.BooleanField(null=True)),
                ('geoid', models.CharField(blank=True, max_length=5, null=True)),
                ('geoidfq', models.CharField(blank=True, max_length=14, null=True)),
                ('statens', models.CharField(blank=True, max_length=8, null=True)),
                ('stusps', models.CharField(blank=True, max_length=2, null=True)),
                ('namelsad', models.CharField(blank=True, max_length=100, null=True)),
                ('cdsessn', models.CharField(blank=True, max_length=41, null=True)),
                ('lsy', models.CharField(blank=True, max_length=4, null=True)),
                ('aland', models.BigIntegerField(blank=True, null=True)),
                ('awater', models.BigIntegerField(blank=True, null=True)),
                ('intptlat', models.CharField(blank=True, max_length=20, null=True)),
                ('intptlon', models.CharField(blank=True, max_length=20, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='places.boundary', verbose_name='parent')),
            ],
            options={
                'verbose_name_plural': 'Boundaries',
            },
        ),
        migrations.CreateModel(
            name='RegionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('overlapping_enabled', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='places.regiongroup', verbose_name='parent')),
            ],
            options={
                'verbose_name_plural': 'Region Groups',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('boundaries', models.ManyToManyField(blank=True, to='places.boundary')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='places.regiongroup')),
            ],
            options={
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='places.location', verbose_name='parent')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='places.site')),
            ],
            options={
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='SiteGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='places.sitegroup', verbose_name='parent')),
            ],
            options={
                'verbose_name_plural': 'Site Groups',
            },
        ),
        migrations.AddField(
            model_name='site',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='places.sitegroup'),
        ),
    ]
