# Generated by Django 5.1.1 on 2024-12-01 17:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boundary',
            name='aland',
            field=models.IntegerField(blank=True, null=True, verbose_name=14),
        ),
        migrations.AddField(
            model_name='boundary',
            name='awater',
            field=models.IntegerField(blank=True, null=True, verbose_name=14),
        ),
        migrations.AddField(
            model_name='boundary',
            name='geoid',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='boundary',
            name='geoidfq',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='boundary',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='boundary',
            name='intpntlat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boundary',
            name='intpntlon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boundary',
            name='lsy',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='boundary',
            name='namelsad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='boundary',
            name='level',
            field=models.CharField(choices=[('nation', 'National'), ('state', 'State'), ('county', 'County'), ('municipality', 'Municipality'), ('legislative', 'Legislative'), ('organizational', 'Organizational')], max_length=100),
        ),
    ]
