# Generated by Django 4.1.2 on 2022-11-27 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_regiongroup_sitegroup_remove_region_org_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boundary',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='location',
            name='parent',
        ),
    ]
