# Generated by Django 5.1.1 on 2024-12-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_boundary_aland_boundary_awater_boundary_geoid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundary',
            name='lsy',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
