# Generated by Django 5.1.1 on 2024-12-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_boundary_lsy'),
    ]

    operations = [
        migrations.AddField(
            model_name='boundary',
            name='cdsessn',
            field=models.CharField(blank=True, max_length=41, null=True),
        ),
    ]
