# Generated by Django 4.1.4 on 2022-12-09 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_site_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='sitegroup',
            options={'verbose_name_plural': 'Site Groups'},
        ),
    ]
