# Generated by Django 5.1.1 on 2024-12-02 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_boundary_cdsessn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boundary',
            old_name='intpntlat',
            new_name='intptlat',
        ),
        migrations.RenameField(
            model_name='boundary',
            old_name='intpntlon',
            new_name='intptlon',
        ),
    ]
