# Generated by Django 5.1.1 on 2024-12-02 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_rename_intpntlat_boundary_intptlat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundary',
            name='intptlat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='boundary',
            name='intptlon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
