# Generated by Django 4.1.4 on 2022-12-17 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0005_alter_location_options_alter_sitegroup_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="regiongroup",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="places.regiongroup",
                verbose_name="parent",
            ),
        ),
        migrations.AddField(
            model_name="sitegroup",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="places.sitegroup",
                verbose_name="parent",
            ),
        ),
    ]
