# Generated by Django 5.1.1 on 2024-12-02 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_boundary_intptlat_alter_boundary_intptlon'),
    ]

    operations = [
        migrations.AddField(
            model_name='boundary',
            name='statens',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='boundary',
            name='stusps',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
