# Generated by Django 4.1.5 on 2023-01-14 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_regiongroup_parent_sitegroup_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='places.regiongroup'),
        ),
    ]
